apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  labels:
    {{- include "trading.labels" . | nindent 4 }}
    {{- include "trading.postgresql.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgresql.replicas }}
  selector:
    matchLabels:
      {{- include "trading.postgresql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.postgresql.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "trading.labels" . | nindent 8 }}
        {{- include "trading.postgresql.selectorLabels" . | nindent 8 }}
        {{- with .Values.postgresql.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.postgresql.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          ports:
            - name: tcp
              containerPort: {{ .Values.postgresql.port }}
              protocol: TCP
          {{- with .Values.postgresql.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.postgresql.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.postgresql.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
