apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-persistent-volume-claim
  labels:
    {{- include "trading.labels" . | nindent 4 }}
    {{- include "trading.postgresql.selectorLabels" . | nindent 4 }}
spec:
  {{- with .Values.postgresql.persistence.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
