apiVersion: batch/v1
kind: CronJob
metadata:
  name: aurora-cronjob
  labels:
    {{- include "trading.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.aurora.schedule | quote }}
  timeZone: {{ .Values.aurora.timeZone }}
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.aurora.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "trading.labels" . | nindent 12 }}
            {{- with .Values.aurora.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- with .Values.aurora.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.aurora.image.repository }}:{{ .Values.aurora.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.aurora.image.pullPolicy }}
              resources:
                {{- toYaml .Values.aurora.resources | nindent 16 }}
              {{- with .Values.aurora.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- with .Values.aurora.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: {{ .Values.aurora.restartPolicy }}
