apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    {{- include "trading.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      {{- include "trading.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.redis.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "trading.labels" . | nindent 8 }}
        {{- with .Values.redis.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.redis.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: tcp
              containerPort: {{ .Values.redis.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.redis.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.redis.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- with .Values.redis.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.redis.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
