apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: phoenix-http-route
  labels:
    {{- include "trading.labels" . | nindent 4 }}
    {{- include "trading.phoenix.selectorLabels" . | nindent 4 }}
spec:
  {{- with .Values.phoenix.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hostnames:
    {{ toYaml .Values.phoenix.httpRoute.hostnames }}
  rules:
    - backendRefs:
      - name: phoenix-service
        port: {{ .Values.phoenix.service.port }}
