{{- if .Values.phoenix.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: phoenix-service-account
  labels:
    {{- include "trading.labels" . | nindent 4 }}
  {{- with .Values.phoenix.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.phoenix.serviceAccount.automount }}
{{- end }}
