apiVersion: v1
kind: Service
metadata:
  name: phoenix-service
  labels:
    {{- include "trading.labels" . | nindent 4 }}
spec:
  type: {{ .Values.phoenix.service.type }}
  ports:
    - port: {{ .Values.phoenix.service.port }}
      targetPort: {{ .Values.phoenix.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "trading.selectorLabels" . | nindent 4 }}
